# .github/workflows/run_tests.yml

name: Python Tests & Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-qt PyQt5 QScintilla

      - name: Run tests inside Xvfb
        uses: GabrielBB/xvfb-action@v1
        with:
          run: pytest testing/
        env:
          QT_QPA_PLATFORM: offscreen

  bump-version:
    name: Bump version & tag
    runs-on: ubuntu-latest
    needs: test
    if: >
      github.event_name == 'push' &&
      github.ref == 'refs/heads/master' &&
      github.actor != 'github-actions[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Bump patch version in version.py
        shell: bash
        run: |
          set -e
          # Extract current semver from version.py
          CURRENT=$(grep "^__version__" version.py | cut -d '"' -f2)
          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT"
          NEW_PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"
          echo "Bumping $CURRENT → $NEW_VERSION"
          # Overwrite version.py
          sed -i "s/^__version__ = .*/__version__ = \"$NEW_VERSION\"/" version.py

          # Commit and tag
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add version.py
          git commit -m "chore(release): bump version to $NEW_VERSION"
          git tag "v$NEW_VERSION"

      - name: Push commit and tags
        run: |
          git push origin HEAD:master --follow-tags

      - name: Push commit and tags
        run: git push origin HEAD:master --follow-tags
