name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install everything in requirements.txt
          pip install -r requirements.txt
          # Ensure PyQt5 and QScintilla are available for GUI tests
          pip install pytest pytest-qt PyQt5 QScintilla

      - name: Run tests inside Xvfb
        uses: GabrielBB/xvfb-action@v1
        with:
          run: |
            # Explicitly set QT to offscreen (just in case)
            export QT_QPA_PLATFORM=offscreen
            pytest testing/
